name: rio
version: 0.1.2.0
synopsis: A standard library for Haskell
description: See README and Haddocks at <https://www.stackage.org/package/rio>
license: MIT
author: Michael Snoyman
maintainer: michael@snoyman.com
github: commercialhaskell/rio
category: Control
extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.9 && < 10
- ansi-terminal
- bytestring
- containers
- deepseq
- directory
- exceptions
- filepath
- hashable
- microlens
- mtl
- primitive
- text
- time
- typed-process >= 0.2.2.0
- unliftio >= 0.2.6.0
- unordered-containers
- vector

# Just for preprocessor directives
- process

when:
- condition: os(windows)
  then:
    cpp-options: -DWINDOWS
    dependencies:
    - Win32
  else:
    dependencies:
    - unix

library:
  source-dirs: src/
  other-modules:
    - RIO.Prelude.Display
    - RIO.Prelude.Extra
    - RIO.Prelude.IO
    - RIO.Prelude.Lens
    - RIO.Prelude.Logger
    - RIO.Prelude.Reexports
    - RIO.Prelude.Renames
    - RIO.Prelude.RIO
    - RIO.Prelude.Text
    - RIO.Prelude.Trace
    - RIO.Prelude.URef

tests:
  spec:
    source-dirs: test
    main: Spec.hs
    dependencies:
    - rio
    - hspec
